version: '3.8'

services:
  app:
    build: ./frontend
    container_name: research-assistant
    ports:
      - "3000:3000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    volumes:
      - ./.groq:/app/.groq
